apiVersion: v1
kind: Service
metadata:
  name: ignite-service
  labels:
    app: ignite
spec:
  selector:
    app: ignite
  ports:
    - name: client
      port: 10800
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ignite-headless
  labels:
    app: ignite
spec:
  clusterIP: None
  selector:
    app: ignite
  ports:
    - name: discovery
      port: 47500
    - name: comm
      port: 47100
    - name: client
      port: 10800
